name: hello_flutter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  hexcolor: ^2.0.7
  fluttertoast: ^8.0.9
  firebase_auth: ^3.7.0
  cloud_firestore: ^3.4.6
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.1
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.0.0+2
  flutter_native_splash: ^2.2.8




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.10.0


flutter_native_splash:
  image: "assets/images/icon.png"
  background_image: "assets/images/background.png"




flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true


flutter:


  uses-material-design: true



  assets:
    - assets/images/


  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf

    - family: MyFont
      fonts:
        - asset: assets/fonts/font.ttf
          weight: 700

